// <auto-generated />
using BankaSimulasyon.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankaSimulasyon.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260219065825_KullaniciVeHesapEklendi4")]
    partial class KullaniciVeHesapEklendi4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("BankaSimulasyon.Models.Entities.ATM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Konum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AtmLer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AktifMi = true,
                            Konum = "Zeytinburnu Beştelsiz Şube"
                        },
                        new
                        {
                            Id = 2,
                            AktifMi = false,
                            Konum = "Bakırköy Cadde Şube"
                        });
                });

            modelBuilder.Entity("BankaSimulasyon.Models.Entities.AtmKaset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Adet")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AtmId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KritikDeger")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kupur")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotNumarasi")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AtmId");

                    b.ToTable("AtmKasetler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adet = 20,
                            AtmId = 1,
                            KritikDeger = 20,
                            Kupur = 200,
                            SlotNumarasi = 1
                        },
                        new
                        {
                            Id = 2,
                            Adet = 20,
                            AtmId = 1,
                            KritikDeger = 20,
                            Kupur = 100,
                            SlotNumarasi = 2
                        },
                        new
                        {
                            Id = 3,
                            Adet = 20,
                            AtmId = 1,
                            KritikDeger = 20,
                            Kupur = 50,
                            SlotNumarasi = 3
                        },
                        new
                        {
                            Id = 4,
                            Adet = 20,
                            AtmId = 1,
                            KritikDeger = 20,
                            Kupur = 20,
                            SlotNumarasi = 4
                        });
                });

            modelBuilder.Entity("BankaSimulasyon.Models.Entities.Kullanici", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Isim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Soyisim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefonNumarasi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Kullanicilar");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Adres = "Zeytinburnu",
                            Cinsiyet = "Cinsiyet girilmedi",
                            Isim = "BugraTest",
                            Soyisim = "Kaplan",
                            TelefonNumarasi = "Telefon numarası girilmedi"
                        });
                });

            modelBuilder.Entity("BankaSimulasyon.Models.Entities.KullaniciHesap", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Bakiye")
                        .HasColumnType("TEXT");

                    b.Property<int>("HesapNumarasi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("kullaniciId")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("kullaniciId");

                    b.ToTable("KullaniciHesaplari");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Bakiye = 100000m,
                            HesapNumarasi = 0,
                            kullaniciId = 1
                        });
                });

            modelBuilder.Entity("BankaSimulasyon.Models.Entities.AtmKaset", b =>
                {
                    b.HasOne("BankaSimulasyon.Models.Entities.ATM", "Atm")
                        .WithMany("Kasetler")
                        .HasForeignKey("AtmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atm");
                });

            modelBuilder.Entity("BankaSimulasyon.Models.Entities.KullaniciHesap", b =>
                {
                    b.HasOne("BankaSimulasyon.Models.Entities.Kullanici", "kullanici")
                        .WithMany("KullaniciHesapListesi")
                        .HasForeignKey("kullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("kullanici");
                });

            modelBuilder.Entity("BankaSimulasyon.Models.Entities.ATM", b =>
                {
                    b.Navigation("Kasetler");
                });

            modelBuilder.Entity("BankaSimulasyon.Models.Entities.Kullanici", b =>
                {
                    b.Navigation("KullaniciHesapListesi");
                });
#pragma warning restore 612, 618
        }
    }
}
