// <auto-generated />
using BankaSimulasyon.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankaSimulasyon.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260309113018_removeKullaniciHesapIdOnKartlar")]
    partial class removeKullaniciHesapIdOnKartlar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankaSimulasyon.Models.Entities.ATM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("Konum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AtmLer");
                });

            modelBuilder.Entity("BankaSimulasyon.Models.Entities.AtmKaset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<int>("AtmId")
                        .HasColumnType("int");

                    b.Property<int>("KritikDeger")
                        .HasColumnType("int");

                    b.Property<int>("Kupur")
                        .HasColumnType("int");

                    b.Property<int>("SlotNumarasi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AtmId");

                    b.ToTable("AtmKasetler");
                });

            modelBuilder.Entity("BankaSimulasyon.Models.Entities.Kart", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("CVV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KartNumara")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KartSKT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KartTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Kartlar");
                });

            modelBuilder.Entity("BankaSimulasyon.Models.Entities.Kullanici", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyisim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonNumarasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("BankaSimulasyon.Models.Entities.KullaniciHesap", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("Bakiye")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HesapNumarasi")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("KullaniciHesaplari");
                });

            modelBuilder.Entity("BankaSimulasyon.Models.Entities.AtmKaset", b =>
                {
                    b.HasOne("BankaSimulasyon.Models.Entities.ATM", "Atm")
                        .WithMany("Kasetler")
                        .HasForeignKey("AtmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atm");
                });

            modelBuilder.Entity("BankaSimulasyon.Models.Entities.Kart", b =>
                {
                    b.HasOne("BankaSimulasyon.Models.Entities.Kullanici", "kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("kullanici");
                });

            modelBuilder.Entity("BankaSimulasyon.Models.Entities.KullaniciHesap", b =>
                {
                    b.HasOne("BankaSimulasyon.Models.Entities.Kullanici", "kullanici")
                        .WithMany("KullaniciHesapListesi")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("kullanici");
                });

            modelBuilder.Entity("BankaSimulasyon.Models.Entities.ATM", b =>
                {
                    b.Navigation("Kasetler");
                });

            modelBuilder.Entity("BankaSimulasyon.Models.Entities.Kullanici", b =>
                {
                    b.Navigation("KullaniciHesapListesi");
                });
#pragma warning restore 612, 618
        }
    }
}
