// <auto-generated />
using System;
using BankaSimulasyon.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankaSimulasyon.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260403131155_AddedKartKullanilanLimitt")]
    partial class AddedKartKullanilanLimitt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankaSimulasyon.Models.Entities.ATM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("Konum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AtmLer");
                });

            modelBuilder.Entity("BankaSimulasyon.Models.Entities.AtmKaset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<int>("AtmId")
                        .HasColumnType("int");

                    b.Property<int>("KritikDeger")
                        .HasColumnType("int");

                    b.Property<int>("Kupur")
                        .HasColumnType("int");

                    b.Property<int>("SlotNumarasi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AtmId");

                    b.ToTable("AtmKasetler");
                });

            modelBuilder.Entity("BankaSimulasyon.Models.Entities.Kart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("KartGunlukLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KartKalanLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KartKullanilanLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("KartNumara")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("SonIslemTarihi")
                        .HasColumnType("date");

                    b.Property<int>("YanlisGirisSayisi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.ToTable("Kartlar");
                });

            modelBuilder.Entity("BankaSimulasyon.Models.Entities.KartSifre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KartId")
                        .HasColumnType("int");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KartId")
                        .IsUnique();

                    b.ToTable("KartSifreleri");
                });

            modelBuilder.Entity("BankaSimulasyon.Models.Entities.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Isim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MusteriLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Soyisim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("BankaSimulasyon.Models.Entities.AtmKaset", b =>
                {
                    b.HasOne("BankaSimulasyon.Models.Entities.ATM", "Atm")
                        .WithMany("Kasetler")
                        .HasForeignKey("AtmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atm");
                });

            modelBuilder.Entity("BankaSimulasyon.Models.Entities.Kart", b =>
                {
                    b.HasOne("BankaSimulasyon.Models.Entities.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("BankaSimulasyon.Models.Entities.KartSifre", b =>
                {
                    b.HasOne("BankaSimulasyon.Models.Entities.Kart", "Kart")
                        .WithOne("KartSifre")
                        .HasForeignKey("BankaSimulasyon.Models.Entities.KartSifre", "KartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kart");
                });

            modelBuilder.Entity("BankaSimulasyon.Models.Entities.ATM", b =>
                {
                    b.Navigation("Kasetler");
                });

            modelBuilder.Entity("BankaSimulasyon.Models.Entities.Kart", b =>
                {
                    b.Navigation("KartSifre");
                });
#pragma warning restore 612, 618
        }
    }
}
